### ISSUE TITLE
Failure to install package "rhtmlDonut" from GitHub

### ISSUE THREAD

**Issue by GegznaV** [Displayr/rhtmlDonut#45]
```r
remotes::install_github("Displayr/rhtmlDonut")
```

Results in the following warnings:

<details>
<summary>Warnings</summary>

>    Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.australian_city_populations-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.australian_city_populations-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.browser_stats_innerlabels2-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.browser_stats_innerlabels2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.coke_zero_sentiment_unsorted-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.coke_zero_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_diet_survey-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_diet_survey-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_powers_of_2-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_powers_of_2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.diet_pepsi_sentiment_unsorted-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.diet_pepsi_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.usage_example_employment_types-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.usage_example_employment_types-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.australian_city_populations-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.australian_city_populations-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.browser_stats_innerlabels2-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.browser_stats_innerlabels2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_diet_survey-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_diet_survey-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_powers_of_2-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000 data.misc.usage_example_powers_of_2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.coke_zero_sentiment_unsorted-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.coke_zero_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.diet_pepsi_sentiment_unsorted-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.diet_pepsi_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.usage_example_employment_types-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.usage_example_employment_types-snap.png: No such file or directory

</details>

And the following error:

>  ERROR
>   copying to build directory failed

> Error: Failed to install 'rhtmlDonut' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.coke_zero_sentiment_unsorted-snap.png to C:\Users\user\AppData\Local\Temp\RtmpuwAMQZ\Rbuild2fe0a6d36ea\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.coke_zero_sentiment_unsorted-snap.png: No such file or directory
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\Displayr-rhtmlDonut-eeb5450\theSrc\test\snapshots\travis\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600 data.misc.diet_pepsi_sentiment_u

How can this issue be solved?

**Comment by kylezeeuwen** [comment]
Hello @GegznaV,

Looks like Windows is struggling because there is a space in the file path `representative_examples_misc_600x600 data.misc.coke_zero_sentiment_unsorted-snap.png`.

I will see if it is easy to remove those spaces from the tests.

In the meantime you could download the repo locally, then use `devtools::install()` in the local repo directory ?

**Comment by kylezeeuwen** [comment]
Hello again @GegznaV 

The issue you raised identified a bug in my build system that was allowing the creation of file names with spaces. 

I've fixed that here : https://github.com/Displayr/rhtmlBuildUtils/releases/tag/7.0.1 and am using that new version in this branch of rhtmlDonut : https://github.com/Displayr/rhtmlDonut/tree/VIS-591

The branch of donut is available now, and it should be merged before Jan 10, 2021. Thanks for the issue report, and for having a look at rhtmlDonut.

**Comment by sreedta8** [comment]
@kylezeeuwen  Hi I'm trying to install rhtmlDonut and ran into the same error as @GegznaV - I'm on WIndows10.

What is the correct way to install the rhtmlBuildUtils and rhtmlDonut?

I get the following error when I try to install the new version of rhtmlDonut using the R CMD Build method. See below

```
C:\Users\zach.sree\Documents\RScripts\rhtmlDonut-VIS-591>R CMD build rhtmlDonut-VIS-591
* checking for file 'rhtmlDonut-VIS-591/DESCRIPTION' ... OK
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  over-long path
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  over-long path
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  over-long path
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  over-long path
 ERROR
copying to build directory failed
```

**Comment by sreedta8** [comment]
@kylezeeuwen I have tried to install using devtools package and the installation still fails. See the output below:
```
> devtools::install_github("https://github.com/Displayr/rhtmlDonut/tree/VIS-591")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo Displayr/rhtmlDonut@VIS-591
  
  
  
√  checking for file 'C:\Users\zach.sree\AppData\Local\Temp\RtmpuKIFfW\remotes196c5a461306\Displayr-rhtmlDonut-fe38c3a/DESCRIPTION'

  
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_family_home_stats-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_family_home_stats-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
   problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_presidential_traits-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_presidential_traits-snap.png: No such file or direct
  
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_presidential_traits-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_presidential_traits-snap.png: No such file or directory

  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path

  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_full_pie-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_full_pie-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_gradient-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_gradient-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_grouped-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_grouped-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
   problem copying .
  
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_ordered-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_ordered-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_unordered-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_browser_stats_unordered-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_presidential_traits-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_presidential_traits-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
Warnin
  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path

  
  
  
    ERROR
   copying to build directory failed

Error: Failed to install 'rhtmlDonut' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_presidential_traits-snap.png to C:\Users\zach.sree\AppData\Local\Temp\RtmpMFh4bO\Rbuild4e147d80f0c\Displayr-rhtmlDonut-fe38c3a\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_presidential_traits-snap.png: No such file or directory
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
```

**Comment by kylezeeuwen** [comment]
Hello @sreedta8,

rhtmlBuildUtils, rhtmlDonut, and all of the Displayr rhtml* repos are maintained open source, but their primary deploy target are Linux based R servers that are part of  the Displayr infrastructure.

I maintain most of these packages, and I do my dev on a Mac and the code is deployed to Linux servers.

As such these modules do not get any attention for Windows portability. This is not a deliberate thing, just a consequence of my preference and the target environment.

I can help you or someone else troubleshoot these issues, but as I do not have nor want any Windows hardware / virtual environments, and I dont have any experience on these platforms, I cannot take the lead on said troubleshooting.

I notice that both of the install issues on this thread occur in the "theSrc\test\snapshots" directory. This directory is not actually required to use the html widget via R. So this is my first suggestion: fork the repo, create a branch, and completely delete "theSrc\test\snapshots" and then try to install via devtools and post the output 👍

**Comment by sreedta8** [comment]
@kylezeeuwen Thank you for the context of the package targeting Linux platforms. That helps contextualize it better. I will definitely test the install on my Ubuntu machine.
I will test the suggestion you provided for Windows and let you know in a day or two if that solution works. Thank you for the suggestion and your efforts overall.

**Comment by andrewpmk** [comment]
Could you reduce the length of the filenames in those tests to prevent this problem. We were running into errors when installing flipRegression which depends on this package:

```
Downloading GitHub repo Displayr/rhtmlDonut@HEAD
âˆš  checking for file 'C:\Users\slam\AppData\Local\Temp\RtmpSa4haw\remotes45943f655a55\Displayr-rhtmlDonut-84ef77e/DESCRIPTION' (458ms)
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_browser_stats_innerlabels2-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_browser_stats_innerlabels2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_usage_example_diet_survey-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_usage_example_diet_survey-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_usage_example_powers_of_2-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_1000x1000\representative_examples_misc_1000x1000_data_misc_usage_example_powers_of_2-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_coke_zero_sentiment_unsorted-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_coke_zero_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_diet_pepsi_sentiment_unsorted-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_diet_pepsi_sentiment_unsorted-snap.png: No such file or directory
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_usage_example_employment_types-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_usage_example_employment_types-snap.png: No such file or directory
    ERROR
   copying to build directory failed
Error: Failed to install 'flipRegression' from GitHub:
  Failed to install 'flipStandardCharts' from GitHub:
  Failed to install 'rhtmlDonut' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_coke_zero_sentiment_unsorted-snap.png to C:\Users\slam\AppData\Local\Temp\RtmpwrRUKg\Rbuild32303bc66b93\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\representative_examples_misc_600x600\representative_examples_misc_600x600_data_misc_coke_zero_sentiment_unsorted-snap.png: No such file or directory
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\Displayr-rhtmlDonut-84ef77e\theSrc\test\snapshots\local\master\testPlans\rep
```

I ended up using the workaround of cloning rhtmlDonut, removing the test directory, installing from the cloned directory, and then installing flipRegression - took me more than a hour of my time to do this (we're using flipRegression for work at my employer).

**Comment by sreedta8** [comment]
@kylezeeuwen @andrewpmk on my Windows machine deleting the "test" directory did not work to install "rhtmlDonut".

What worked for me was to install the package "remotes" first and then use the following command:

```remotes::install_github("Displayr/rhtmlDonut", build = FALSE, force=TRUE)```

I was able to install rhtmlDonut and the entire suite of the analytical packages from Displayr github repository using the above format including "flipRegression", "flipAnansisofVariance", and "flipStatistics" to name a few

Thank you all for sharing so others could also benefit

**Comment by andrewpmk** [comment]
The following worked for me to install flipRegression (which depends on rhtmlDonut):

1.	Clone the git repository https://github.com/Displayr/rhtmlDonut.git
2.	Remove the directory theSrc/test/ - this is the offending directory which has excessively long file names, but it isn’t needed to install the package
3.	Run devtools::install_local(path = "path") – replace “path” with the directory where you cloned the git repository
4.	Install flipRegression with install_github("Displayr/flipRegression", dependencies = NA). Say no if it asks you to upgrade rhtmlDonut.

**Comment by JustinCCYap** [comment]
This is fixed now as I have shortened the file names causing the issue.
